import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import {GoogleOAuthProvider,GoogleLogin} from '@react-oauth/google';
import {Apple,BarChart3,CalendarDays,ChevronDown,ChevronRight,CircleUserRound,Flame,Home,LogOut,Menu,Plus,Search,Settings,ShieldCheck,Sparkles,Target,Trash2,TrendingUp,Utensils,Droplets,X,MessageCircle,Send,Info, Trophy, Clock3, HeartPulse} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
const GOOGLE_ID=import.meta.env.VITE_GOOGLE_CLIENT_ID||'';
const api=axios.create({baseURL:API});
api.interceptors.request.use(c=>{const t=localStorage.getItem('meal_token');if(t)c.headers.Authorization=`Bearer ${t}`;return c});
const today=()=>new Date().toISOString().slice(0,10);
const moneyless=x=>Number(x||0).toFixed(0);
const unwrap=r=>r?.data?.data??r?.data;

function BowlLogo({small=false}){return <div className={'brand '+(small?'small':'')}><div className="bowl-logo"><span></span><i></i></div><b>Nutri<span>Plan</span></b></div>}
function pct(v,g){return g?Math.min(100,Math.round(v/g*100)):0}
function Ring({value,goal,label,color='orange'}){return <div className={'ring '+color} style={{'--p':`${pct(value,goal)*3.6}deg`}}><div><b>{Math.round(value)}</b><small>{label}</small></div></div>}

function Auth({onAuth}){
 const [mode,setMode]=useState('login'),[f,setF]=useState({username:'',displayName:'',email:'',password:''}),[err,setErr]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();if(busy)return;setErr('');setBusy(true);try{const path=mode==='login'?'/auth/login':'/auth/signup';const body=mode==='login'?{email:f.email.trim(),password:f.password}: {username:f.username.trim(),displayName:f.displayName.trim(),email:f.email.trim(),password:f.password};const r=await api.post(path,body,{timeout:10000});const d=unwrap(r);if(!d?.token||!d?.user)throw new Error('The server returned an unexpected response.');localStorage.setItem('meal_token',d.token);onAuth(d.user)}catch(e){const status=e.response?.status;const serverMessage=e.response?.data?.message;setErr(serverMessage?`${serverMessage}${status?` (HTTP ${status})`:''}`:e.code==='ECONNABORTED'?'Backend request timed out. Make sure the backend is running on port 5000.':e.response?`Request failed with HTTP ${status}. Check the backend terminal for the error.`:'Cannot reach the backend. Start backend with: npm run dev')}finally{setBusy(false)}}
 async function google(credential){setErr('');try{const r=await api.post('/auth/google',{credential});const d=unwrap(r);localStorage.setItem('meal_token',d.token);onAuth(d.user)}catch(e){setErr(e.response?.data?.message||'Google authentication failed.')}}
 return <div className="auth"><div className="auth-left"><BowlLogo/><div className="auth-copy"><p className="eyebrow">MEAL PLANNER · NUTRITION TRACKER</p><h1>Your food.<br/><em>Your goals.</em><br/>Your rhythm.</h1><p>Plan meals, track nutrition, stay hydrated and see your progress — all in one calm, simple workspace.</p></div><div className="auth-orbit o1">🥕</div><div className="auth-orbit o2">🍊</div></div><div className="auth-right"><div className="auth-box"><div className="mobile-brand"><BowlLogo/></div><p className="eyebrow">{mode==='login'?'WELCOME BACK':'CREATE YOUR ACCOUNT'}</p><h2>{mode==='login'?'Let’s pick up where you left off.':'Build your nutrition routine.'}</h2><p className="muted">{mode==='login'?'Sign in to access your meals and progress.':'Your profile stores your goals and preferences.'}</p>{GOOGLE_ID?<><GoogleOAuthProvider clientId={GOOGLE_ID}><GoogleLogin onSuccess={r=>google(r.credential)} onError={()=>setErr('Google sign-in was not completed.')} width="100%" text="continue_with"/></GoogleOAuthProvider><div className="or"><span/>or<span/></div></>:<div className="google-missing"><Info size={16}/><span>Google sign-in is ready, but <b>VITE_GOOGLE_CLIENT_ID</b> is not configured yet.</span></div>}<form onSubmit={submit}>
 {mode==='signup'&&<><label>Username<input required value={f.username} onChange={e=>setF({...f,username:e.target.value})} placeholder="yourusername"/></label><label>Display name<input required value={f.displayName} onChange={e=>setF({...f,displayName:e.target.value})} placeholder="Your name"/></label></>}
 <label>Email<input required type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} placeholder="you@example.com"/></label><label>Password<input required type="password" minLength="6" value={f.password} onChange={e=>setF({...f,password:e.target.value})} placeholder="At least 6 characters"/></label>{err&&<div className="error">{err}</div>}<button type="submit" className="primary full" disabled={busy}>{busy?'Connecting…':mode==='login'?'Sign in':'Create account'}<ChevronRight size={18}/></button></form><p className="switch">{mode==='login'?'New here?':'Already have an account?'} <button type="button" onClick={()=>{setMode(mode==='login'?'signup':'login');setErr('');setF({username:'',displayName:'',email:'',password:''})}}>{mode==='login'?'Create account':'Sign in'}</button></p></div></div></div>
}

const nav=[['dashboard','Dashboard',Home],['meals','Meal Planner',Utensils],['foods','Food Library',Apple],['water','Water Tracker',Droplets],['progress','Progress',TrendingUp],['analytics','Analytics',BarChart3],['achievements','Achievements',Trophy],['profile','Profile',CircleUserRound],['settings','Settings',Settings]];
function Sidebar({active,setActive,user,logout,open,setOpen}){return <aside className={'sidebar '+(open?'open':'')}><div className="side-head"><BowlLogo/><button className="icon mobile-only" onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([id,l,I])=><button className={active===id?'active':''} key={id} onClick={()=>{setActive(id);setOpen(false)}}><I size={18}/>{l}</button>)}</nav><div className="side-user"><div className="avatar">{(user?.displayName||'U')[0].toUpperCase()}</div><div className="user-name"><b>{user?.displayName||'User'}</b><small>@{user?.username||'account'}</small></div><button className="logout" onClick={logout}><LogOut size={17}/></button></div></aside>}
function Top({title,onMenu,user,onChat}){return <header className="top"><button className="icon mobile-only" onClick={onMenu}><Menu/></button><div><span className="mobile-brand-title">NutriPlan</span><h2>{title}</h2></div><div className="top-right"><button className="icon" onClick={onChat}><MessageCircle size={18}/></button><div className="avatar">{(user?.displayName||'U')[0].toUpperCase()}</div></div></header>}

function Dashboard({user,setPage}){
 const [loading,setLoading]=useState(true),[data,setData]=useState(null),[water,setWater]=useState(null),[err,setErr]=useState('');
 useEffect(()=>{(async()=>{try{const [meals,wa]=await Promise.all([api.get(`/meals/date/${today()}`),api.get(`/water/${today()}`)]);setData(unwrap(meals));setWater(unwrap(wa))}catch(e){setErr(e.response?.data?.message||'Could not load your dashboard.')}finally{setLoading(false)}})()},[]);
 if(loading)return <Loading/>; if(err)return <ErrorPanel text={err}/>;
 const t=data?.dailyTotals||{},g=user?.goals||{};const meals=data?.meals||[];const waterGoal=water?.goal||8;const glasses=water?.glasses||0;
 return <div className="page"><div className="hero"><div><p className="eyebrow">{new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</p><h1>Good to see you, {user?.displayName||user?.username} <span>👋</span></h1><p className="muted">Here’s what your day looks like so far.</p></div><button className="primary" onClick={()=>setPage('meals')}><Plus size={17}/> Log a meal</button></div>
 <div className="stats"><div className="stat feature"><div><span className="stat-label"><Flame/> Calories</span><strong>{moneyless(t.calories)}</strong><small>of {g.dailyCalorieGoal??0} kcal</small><div className="bar"><i style={{width:`${pct(t.calories,g.dailyCalorieGoal||0)}%`}}/></div></div><Ring value={t.calories} goal={g.dailyCalorieGoal||0} label="kcal"/></div><div className="stat"><span className="stat-label"><HeartPulse/> Protein</span><strong>{moneyless(t.protein)}<small> g</small></strong><div className="bar"><i style={{width:`${pct(t.protein,g.proteinGoal||0)}%`}}/></div><small>Goal {g.proteinGoal??0}g</small></div><div className="stat"><span className="stat-label"><Droplets/> Water</span><strong>{glasses}<small> / {waterGoal} glasses</small></strong><div className="bar blue"><i style={{width:`${pct(glasses,waterGoal)}%`}}/></div><button className="text" onClick={()=>setPage('water')}>Track water <ChevronRight size={14}/></button></div></div>
 <div className="two-col"><section className="panel"><div className="panel-head"><div><p className="eyebrow">TODAY</p><h3>Your meals</h3></div><button className="text" onClick={()=>setPage('meals')}>Planner <ChevronRight size={14}/></button></div>{meals.length?<div className="meal-list">{meals.map(m=><MealRow key={m._id} meal={m}/>)}</div>:<Empty icon="🍽️" title="No meals logged yet" text="Start with your first meal today." action={()=>setPage('meals')}/>}</section><section className="panel"><div className="panel-head"><div><p className="eyebrow">NUTRITION</p><h3>Daily balance</h3></div><Sparkles size={19}/></div><Macro name="Protein" value={t.protein} goal={g.proteinGoal}/><Macro name="Carbs" value={t.carbs} goal={g.carbsGoal}/><Macro name="Fats" value={t.fats} goal={g.fatsGoal}/><div className="insight"><Sparkles size={16}/><span>These numbers come from the meals you’ve logged today.</span></div></section></div></div>
}
function MealRow({meal,onDelete}){return <div className="meal-row"><div className="meal-emoji">{meal.mealType==='breakfast'?'🍳':meal.mealType==='lunch'?'🍛':meal.mealType==='dinner'?'🍲':'🍎'}</div><div className="meal-info"><b>{meal.mealType[0].toUpperCase()+meal.mealType.slice(1)}</b><span>{meal.foodItems?.map(x=>x.name).join(', ')}</span></div><strong>{Math.round(meal.totalNutrition?.calories||0)}<small> kcal</small></strong>{onDelete&&<button className="delete" onClick={()=>onDelete(meal._id)}><Trash2 size={15}/></button>}</div>}
function Macro({name,value,goal}){return <div className="macro"><span>{name}<b>{Math.round(value||0)}g / {goal||0}g</b></span><div><i style={{width:`${pct(value,goal||0)}%`}}/></div></div>}

function Meals(){const [date,setDate]=useState(today()),[data,setData]=useState(null),[foods,setFoods]=useState([]),[selected,setSelected]=useState([]),[type,setType]=useState('breakfast'),[notes,setNotes]=useState(''),[mood,setMood]=useState('normal'),[query,setQuery]=useState(''),[err,setErr]=useState('');
 const load=async()=>{try{const [m,f]=await Promise.all([api.get(`/meals/date/${date}`),query?api.get(`/foods/search?query=${encodeURIComponent(query)}`):api.get('/foods/category/breakfast')]);setData(unwrap(m));setFoods(unwrap(f)||[])}catch(e){setErr(e.response?.data?.message||'Unable to load meals/foods')}};useEffect(()=>{load()},[date]);useEffect(()=>{const id=setTimeout(()=>load(),350);return()=>clearTimeout(id)},[query]);
 function addFood(f){setSelected(s=>s.some(x=>x._id===f._id)?s:[...s,{...f,quantity:1}])};function removeFood(id){setSelected(s=>s.filter(x=>x._id!==id))}
 async function save(){if(!selected.length)return;try{await api.post('/meals',{date,mealType:type,foodItems:selected.map(f=>({name:f.name,quantity:f.quantity,unit:f.servingSize?.unit||'serving',calories:f.nutrition.calories,protein:f.nutrition.protein,carbs:f.nutrition.carbs,fats:f.nutrition.fats,fiber:f.nutrition.fiber,sugar:f.nutrition.sugar})),notes,mood});setSelected([]);setNotes('');await load()}catch(e){setErr(e.response?.data?.message||'Could not save meal')}}
 async function del(id){try{await api.delete(`/meals/${id}`);await load()}catch(e){setErr(e.response?.data?.message||'Could not delete meal')}}
 return <div className="page"><div className="page-title"><div><p className="eyebrow">MEAL PLANNER</p><h1>Build today’s meals</h1><p className="muted">Use the foods already seeded in your backend and log exactly what you ate.</p></div><input className="date-input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div>{err&&<div className="error">{err}</div>}<div className="planner"><section className="panel"><div className="panel-head"><div><p className="eyebrow">FOOD LIBRARY</p><h3>Choose food</h3></div></div><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search idli, dosa, paneer, biryani…"/></div><div className="food-mini-grid">{foods.map(f=><button className="food-mini" key={f._id} onClick={()=>addFood(f)}><span>{f.category==='breakfast'?'🍳':f.category==='protein'?'🥘':f.category==='grains'?'🍚':f.category==='dairy'?'🥛':f.category==='fruits'?'🍎':'🥗'}</span><b>{f.name}</b><small>{f.nutrition.calories} kcal · {f.servingSize?.amount}{f.servingSize?.unit}</small></button>)}</div></section><section className="panel builder"><div className="panel-head"><div><p className="eyebrow">NEW MEAL</p><h3>Meal details</h3></div></div><div className="segmented">{['breakfast','lunch','dinner','snacks'].map(x=><button className={type===x?'on':''} onClick={()=>setType(x)} key={x}>{x}</button>)}</div>{selected.length?<div className="selected">{selected.map(f=><div className="selected-row" key={f._id}><span>{f.name}</span><small>{f.nutrition.calories} kcal</small><button onClick={()=>removeFood(f._id)}><X size={14}/></button></div>)}</div>:<div className="empty-box">Select foods from the library to build this meal.</div>}<label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="How did this meal feel?"/></label><label>Mood<select value={mood} onChange={e=>setMood(e.target.value)}>{['energetic','normal','tired','hungry','satisfied'].map(x=><option key={x}>{x}</option>)}</select></label><button className="primary full" disabled={!selected.length} onClick={save}>Save meal <Plus size={17}/></button><hr/><p className="eyebrow">LOGGED FOR {date}</p>{data?.meals?.length?<div className="meal-list">{data.meals.map(m=><MealRow key={m._id} meal={m} onDelete={del}/>)}</div>:<p className="muted small">Nothing logged for this date.</p>}</section></div></div>}

function Foods(){
 const [q,setQ]=useState(''),[cat,setCat]=useState('breakfast'),[foods,setFoods]=useState([]),[custom,setCustom]=useState(false),[err,setErr]=useState(''),[loading,setLoading]=useState(false);
 const cats=['breakfast','protein','vegetables','fruits','grains','dairy','snacks','beverages','other'];
 async function load(){
  setLoading(true);setErr('');
  try{
   let r;
   if(custom){
    r=await api.get('/foods/custom');
   }else if(q.trim()){
    r=await api.get(`/foods/search?query=${encodeURIComponent(q.trim())}`);
   }else{
    r=await api.get(`/foods/category/${cat}`);
   }
   setFoods(unwrap(r)||[]);
  }catch(e){setFoods([]);setErr(e.response?.data?.message||'Unable to load foods. Make sure the backend is running.')}
  finally{setLoading(false)}
 }
 useEffect(()=>{const id=setTimeout(load,200);return()=>clearTimeout(id)},[q,cat,custom]);
 const toggleCustom=()=>{setCustom(v=>!v);setQ('')};
 return <div className="page">
  <div className="page-title"><div><p className="eyebrow">FOOD LIBRARY</p><h1>Indian food, properly tracked.</h1><p className="muted">Browse South Indian, North Indian and everyday foods with nutrition for the listed serving.</p></div></div>
  <div className="food-toolbar"><div className="search wide"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search idli, dosa, paneer, biryani…"/></div><button className={custom?'primary':'secondary'} onClick={toggleCustom}>{custom?'All foods':'My custom foods'}</button></div>
  {!custom&& !q.trim()&&<div className="chips">{cats.map(c=><button className={cat===c?'on':''} onClick={()=>setCat(c)} key={c}>{c.replace('-',' ')}</button>)}</div>}
  <p className="food-note">Nutrition values are approximate and can vary with recipe, ingredients and preparation method.</p>
  {err&&<div className="error">{err}</div>}
  {loading?<Loading/>:<div className="food-grid">{foods.map(f=><div className="food-card" key={f._id}>
   <div className="food-top"><div className="food-emoji">{f.category==='breakfast'?'🍳':f.category==='protein'?'🥘':f.category==='grains'?'🍚':f.category==='dairy'?'🥛':f.category==='fruits'?'🍎':f.category==='beverages'?'🥤':f.category==='snacks'?'🥟':'🥗'}</div><span className="pill">{f.category}</span></div>
   <b>{f.name}</b><small>{f.servingSize?.amount} {f.servingSize?.unit}</small>
   <div className="food-nut"><span><b>{f.nutrition.calories}</b> kcal</span><span><b>{f.nutrition.protein}</b>g protein</span></div>
   <div className="food-macros"><span>C {f.nutrition.carbs}g</span><span>F {f.nutrition.fats}g</span><span>Fiber {f.nutrition.fiber}g</span></div>
   <div className="tags">{(f.tags||[]).slice(0,3).map(t=><span key={t}>#{t}</span>)}</div>
  </div>)}</div>}
  {!loading&&!foods.length&&<Empty icon="🥗" title={custom?'No custom foods yet':'No matching foods'} text={custom?'Create custom foods from the API when you need your own recipes.':'Try another food name or category.'}/>} 
 </div>
}
function Water(){const [d,setD]=useState(null),[err,setErr]=useState('');const date=today();async function load(){try{setD(unwrap(await api.get(`/water/${date}`)))}catch(e){setErr(e.response?.data?.message||'Unable to load water data')}}useEffect(()=>{load()},[]);async function add(){try{setD(unwrap(await api.post(`/water/${date}/increment`)))}catch(e){setErr(e.response?.data?.message||'Unable to add water')}}if(!d)return <div className="page"><Loading/></div>;return <div className="page"><div className="page-title"><div><p className="eyebrow">HYDRATION</p><h1>Water, one glass at a time.</h1><p className="muted">Your backend tracks glasses and milliliters for each day.</p></div></div>{err&&<div className="error">{err}</div>}<div className="water-panel panel"><div className="water-ring"><Ring value={d.glasses} goal={d.goal} label="glasses" color="blue"/></div><div><p className="eyebrow">TODAY</p><h2>{d.glasses} <small>/ {d.goal} glasses</small></h2><p className="muted">{d.milliliters} ml recorded.</p><div className="bar blue"><i style={{width:`${pct(d.glasses,d.goal)}%`}}/></div><button className="primary" onClick={add}><Plus size={17}/> Add 250 ml</button></div></div></div>}

function Progress(){const [rows,setRows]=useState([]),[form,setForm]=useState({date:today(),weight:'',bodyFatPercentage:'',notes:''}),[err,setErr]=useState('');async function load(){try{setRows(unwrap(await api.get('/progress?days=90'))||[])}catch(e){setErr(e.response?.data?.message||'Unable to load progress')}}useEffect(()=>{load()},[]);async function add(e){e.preventDefault();try{await api.post('/progress',{...form,weight:Number(form.weight),bodyFatPercentage:form.bodyFatPercentage?Number(form.bodyFatPercentage):undefined});setForm({...form,weight:'',bodyFatPercentage:'',notes:''});load()}catch(e){setErr(e.response?.data?.message||'Could not save progress')}}async function del(id){try{await api.delete(`/progress/${id}`);load()}catch(e){setErr(e.response?.data?.message||'Could not delete progress')}}return <div className="page"><div className="page-title"><div><p className="eyebrow">PROGRESS</p><h1>See your real trend.</h1><p className="muted">Only entries recorded in your account appear here.</p></div></div>{err&&<div className="error">{err}</div>}<div className="progress-layout"><form className="panel form" onSubmit={add}><div className="panel-head"><h3>Record progress</h3><TrendingUp/></div><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} required/></label><label>Weight (kg)<input type="number" step="0.1" value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})} required/></label><label>Body fat %<input type="number" step="0.1" value={form.bodyFatPercentage} onChange={e=>setForm({...form,bodyFatPercentage:e.target.value})}/></label><label>Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary full">Save entry</button></form><section className="panel"><div className="panel-head"><div><p className="eyebrow">HISTORY</p><h3>Last 90 days</h3></div></div>{rows.length?<div className="history">{rows.map(r=><div className="history-row" key={r._id}><div><b>{new Date(r.date).toLocaleDateString()}</b><small>{r.notes||'Progress entry'}</small></div><strong>{r.weight} kg</strong><button className="delete" onClick={()=>del(r._id)}><Trash2 size={15}/></button></div>)}</div>:<Empty icon="📈" title="No progress entries" text="Record your first measurement to start your history."/>}</section></div></div>}

function Analytics(){const [a,setA]=useState(null),[err,setErr]=useState('');useEffect(()=>{api.get('/meals/analytics?days=7').then(r=>setA(unwrap(r))).catch(e=>setErr(e.response?.data?.message||'Unable to load analytics'))},[]);if(!a)return <div className="page">{err?<ErrorPanel text={err}/>:<Loading/>}</div>;return <div className="page"><div className="page-title"><div><p className="eyebrow">ANALYTICS</p><h1>Your last 7 days.</h1><p className="muted">Calculated from your logged meals.</p></div></div><div className="stats three"><div className="stat"><span className="stat-label"><Flame/> Total calories</span><strong>{Math.round(a.totalCalories)}</strong></div><div className="stat"><span className="stat-label"><HeartPulse/> Total protein</span><strong>{Math.round(a.totalProtein)}<small> g</small></strong></div><div className="stat"><span className="stat-label"><CalendarDays/> Days tracked</span><strong>{a.daysTracked}</strong></div></div><section className="panel"><div className="panel-head"><div><p className="eyebrow">DAILY BREAKDOWN</p><h3>Calories by day</h3></div></div>{Object.keys(a.dailyBreakdown||{}).length?<div className="analytics-list">{Object.entries(a.dailyBreakdown).map(([d,v])=><div className="analytic-row" key={d}><span>{new Date(d).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><div><div className="bar"><i style={{width:`${Math.min(100,(v.calories/(a.averageCalories||1))*50)}%`}}/></div></div><b>{Math.round(v.calories)} kcal</b></div>)}</div>:<Empty icon="📊" title="No analytics yet" text="Log meals to populate your weekly analytics."/>}</section></div>}
function Achievements({user}){const a=user?.achievements||[];return <div className="page"><div className="page-title"><div><p className="eyebrow">MILESTONES</p><h1>Achievements</h1><p className="muted">These are the achievements stored on your account.</p></div></div><div className="achievement-head panel"><div className="trophy"><Trophy/></div><div><h2>{a.length}</h2><p>recorded achievements</p></div><div className="streak"><Flame/><b>{user?.streak?.currentStreak||0}</b><span>day streak</span></div></div><div className="achievement-grid">{a.length?a.map((x,i)=><div className="achievement" key={i}><Trophy size={21}/><b>{x}</b></div>):<Empty icon="🏆" title="No achievements recorded" text="Keep using the tracker and your backend can add achievements when that logic is implemented."/>}</div></div>}
function Profile({user,setUser}){const [f,setF]=useState({displayName:user.displayName||'',currentWeight:user.currentWeight||'',height:user.height||'',age:user.age||'',gender:user.gender||'other',goals:user.goals||{},preferences:user.preferences||{},settings:user.settings||{}}),[msg,setMsg]=useState('');async function save(e){e.preventDefault();try{const r=await api.put('/auth/profile',{...f,currentWeight:f.currentWeight?Number(f.currentWeight):null,height:f.height?Number(f.height):null,age:f.age?Number(f.age):null});const u=unwrap(r);setUser(u);setMsg('Profile saved.')}catch(e){setMsg(e.response?.data?.message||'Could not save profile')}}return <div className="page"><div className="page-title"><div><p className="eyebrow">PROFILE</p><h1>Your goals & preferences.</h1><p className="muted">These fields map to the User model in your backend.</p></div></div><form className="profile-form" onSubmit={save}><section className="panel form"><h3>Basics</h3><label>Display name<input value={f.displayName} onChange={e=>setF({...f,displayName:e.target.value})}/></label><div className="two"><label>Weight (kg)<input value={f.currentWeight} onChange={e=>setF({...f,currentWeight:e.target.value})}/></label><label>Height (cm)<input value={f.height} onChange={e=>setF({...f,height:e.target.value})}/></label></div><div className="two"><label>Age<input value={f.age} onChange={e=>setF({...f,age:e.target.value})}/></label><label>Gender<select value={f.gender} onChange={e=>setF({...f,gender:e.target.value})}><option>male</option><option>female</option><option>other</option></select></label></div></section><section className="panel form"><h3>Daily goals</h3>{[['dailyCalorieGoal','Calories'],['proteinGoal','Protein (g)'],['carbsGoal','Carbs (g)'],['fatsGoal','Fats (g)']].map(([k,l])=><label key={k}>{l}<input type="number" value={f.goals?.[k]??''} onChange={e=>setF({...f,goals:{...f.goals,[k]:Number(e.target.value)}})}/></label>)}<label>Goal type<select value={f.goals?.goalType||'maintenance'} onChange={e=>setF({...f,goals:{...f.goals,goalType:e.target.value}})}>{['weight_loss','weight_gain','maintenance','muscle_gain'].map(x=><option key={x}>{x}</option>)}</select></label></section><div className="save-row">{msg&&<span>{msg}</span>}<button className="primary">Save profile</button></div></form></div>}
function SettingsPage({user,setUser}){const [dark,setDark]=useState(user.settings?.theme==='dark'),[notes,setNotes]=useState(user.settings?.notifications!==false);async function save(){try{const r=await api.put('/auth/profile',{settings:{...user.settings,theme:dark?'dark':'light',notifications:notes}});setUser(unwrap(r))}catch{}}return <div className="page"><div className="page-title"><div><p className="eyebrow">SETTINGS</p><h1>Make NutriPlan yours.</h1><p className="muted">These switches update your stored account settings.</p></div></div><div className="settings panel"><Setting icon={Settings} title="Theme" text="Use the theme stored in your profile." right={<select value={dark?'dark':'light'} onChange={e=>setDark(e.target.value==='dark')}><option value="light">Light</option><option value="dark">Dark</option></select>}/><Setting icon={ShieldCheck} title="Notifications" text="Keep notification preference in your account." right={<input type="checkbox" checked={notes} onChange={e=>setNotes(e.target.checked)}/>}/><button className="primary" onClick={save}>Save settings</button></div></div>}
function Setting({icon:Icon,title,text,right}){return <div className="setting"><div className="setting-icon"><Icon size={18}/></div><div><b>{title}</b><p>{text}</p></div>{right}</div>}
function Chatbot(){const [open,setOpen]=useState(false),[input,setInput]=useState(''),[msgs,setMsgs]=useState([{from:'bot',text:'Hi! I’m your Nutrition Coach. I can explain nutrition data and help you use the tracker. The current backend does not expose an AI/chat endpoint, so I won’t pretend to send messages to an AI service that isn’t connected.'}]);function send(){if(!input.trim())return;setMsgs(m=>[...m,{from:'user',text:input},{from:'bot',text:'I can help with the data already available in this app, but an AI chat API is not present in the supplied backend. Add a chat endpoint/provider when you want live AI answers.'}]);setInput('')}return <>{open&&<div className="chat"><div className="chat-head"><div><b>Nutrition Coach</b><small>Tracker assistant</small></div><button onClick={()=>setOpen(false)}><X size={17}/></button></div><div className="chat-body">{msgs.map((m,i)=><div className={'bubble '+m.from} key={i}>{m.text}</div>)}</div><div className="chat-input"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask about your tracker…"/><button onClick={send}><Send size={16}/></button></div></div>}<button className="chat-fab" onClick={()=>setOpen(!open)}><MessageCircle/></button></>}
function Loading(){return <div className="loading"><div className="spinner"/>Loading your data…</div>}function ErrorPanel({text}){return <div className="panel error-panel"><Info size={20}/><div><b>Couldn’t load this section</b><p>{text}</p></div></div>}function Empty({icon,title,text,action}){return <div className="empty"><div>{icon}</div><b>{title}</b><p>{text}</p>{action&&<button className="secondary" onClick={action}>Get started</button>}</div>}

function App(){const [user,setUser]=useState(null),[page,setPage]=useState('dashboard'),[mobile,setMobile]=useState(false),[chat,setChat]=useState(false);useEffect(()=>{const t=localStorage.getItem('meal_token');if(t)api.get('/auth/me').then(r=>setUser(unwrap(r))).catch(()=>localStorage.removeItem('meal_token'))},[]);function logout(){localStorage.removeItem('meal_token');setUser(null)}if(!user)return <Auth onAuth={setUser}/>;const titles=Object.fromEntries(nav.map(x=>[x[0],x[1]]));return <div className="app"><Sidebar active={page} setActive={setPage} user={user} logout={logout} open={mobile} setOpen={setMobile}/><main className="main"><Top title={titles[page]} onMenu={()=>setMobile(true)} user={user} onChat={()=>setChat(!chat)}/>{page==='dashboard'&&<Dashboard user={user} setPage={setPage}/>} {page==='meals'&&<Meals/>}{page==='foods'&&<Foods/>}{page==='water'&&<Water/>}{page==='progress'&&<Progress/>}{page==='analytics'&&<Analytics/>}{page==='achievements'&&<Achievements user={user}/>} {page==='profile'&&<Profile user={user} setUser={setUser}/>} {page==='settings'&&<SettingsPage user={user} setUser={setUser}/>}<Chatbot/></main></div>}
createRoot(document.getElementById('root')).render(<App/>);
